### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by santosh61** [ViperOS/android_frameworks_base#1]
target thumb C++: libandroid_runtime <= frameworks/base/core/jni/android/graphics/BitmapFactory.cpp
frameworks/base/core/jni/android/graphics/BitmapFactory.cpp:591:27: error: no member named 'kCallerPasses_Ownership' in 'SkFILEStream'

**Comment by MacTavishAO** [comment]
Merge this commits:
https://github.com/Viper-Project/android_frameworks_base/pull/2
https://github.com/Viper-Project/android_frameworks_base/pull/3
