### ISSUE TITLE
Camera does not work well

### ISSUE THREAD

**Issue by zaparenok3947** [ViperOS/android_frameworks_base#4]
On my LG L90 and Viper OS (Viper-w7-20171024-Coral-v3.1.1-Final-N.zip) camera does not work as photo. But worked as video, and as panoramio well. Error occured after I tried to make an shoot (even in video as touch to screen in video recording mode). I see shutting sound and application goes down with error: "an unknown error occurred, the application will be closed" I even tried to clear cache, change save place (phone memory and sd) and other cameras like OpenCamera, SnapCamera, Google Camera. Still no results. Please, help me. I love your smooth and very cool ROM!! Thank you and best regards, Andrew

**Comment by rkschunk** [comment]
this device is no longer supported by our team, look for the G + community for questions, github is not fit for this.

**Comment by BIRDManJ** [comment]
@rkschunk :(
